sudo: false
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
notifications:
  email: false
services:
  - redis-server
node_js:
  - 'stable'
install:
  - npm install
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test:coverage-travis
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
